### ISSUE TITLE
issue in 

### ISSUE THREAD

**Issue by ayushi-3536** [IBM/inFairness#59]
Hi,

I was trying to run the basic example provided here: https://hub.gke2.mybinder.org/user/ibm-infairness-h9o8a789/doc/workspaces/auto-6/tree/examples/adult-income-prediction/adult_income_prediction.ipynb
However I am running into issue :
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [10], in <cell line: 8>()
      5 distance_x = distances.LogisticRegSensitiveSubspace()
      6 distance_y = distances.SquaredEuclideanDistance()
----> 8 distance_x.fit(X_train, protected_idxs)
      9 distance_y.fit(num_dims=output_size)
     11 distance_x.to(device)

File /srv/conda/envs/notebook/lib/python3.8/site-packages/inFairness/distances/logistic_sensitive_subspace.py:77, in LogisticRegSensitiveSubspace.fit(self, data_X, data_SensitiveAttrs, protected_idxs, keep_protected_idxs, autoinfer_device)
     42 """Fit Logistic Regression Sensitive Subspace distance metric
     43 
     44 Parameters
   (...)
     73         on CPU.
     74 """
     76 if data_SensitiveAttrs is not None and protected_idxs is None:
---> 77     basis_vectors_ = self.compute_basis_vectors_data(
     78         X_train=data_X, y_train=data_SensitiveAttrs
     79     )
     81 elif data_SensitiveAttrs is None and protected_idxs is not None:
     82     basis_vectors_ = self.compute_basis_vectors_protected_idxs(
     83         data_X,
     84         protected_idxs=protected_idxs,
     85         keep_protected_idxs=keep_protected_idxs,
     86     )

File /srv/conda/envs/notebook/lib/python3.8/site-packages/inFairness/distances/logistic_sensitive_subspace.py:164, in LogisticRegSensitiveSubspace.compute_basis_vectors_data(self, X_train, y_train)
    161 X_train = datautils.convert_tensor_to_numpy(X_train)
    162 y_train = datautils.convert_tensor_to_numpy(y_train)
--> 164 self.__assert_sensitiveattrs_binary__(y_train)
    166 basis_vectors_ = []
    167 outdim = y_train.shape[-1]

File /srv/conda/envs/notebook/lib/python3.8/site-packages/inFairness/distances/logistic_sensitive_subspace.py:185, in LogisticRegSensitiveSubspace.__assert_sensitiveattrs_binary__(self, sensitive_attrs)
    183 def __assert_sensitiveattrs_binary__(self, sensitive_attrs):
--> 185     assert validationutils.is_tensor_binary(
    186         sensitive_attrs
    187     ), "Sensitive attributes are required to be binary to learn the metric. Please binarize these attributes before fitting the metric."

File /srv/conda/envs/notebook/lib/python3.8/site-packages/inFairness/utils/validationutils.py:19, in is_tensor_binary(data)
      5 """Checks if the data is binary (0/1) or not. Return True if it is binary data
      6 
      7 Parameters
   (...)
     15         True if data is binary. False if not
     16 """
     18 nonbindata = (data != 0) & (data != 1)
---> 19 has_nonbin_data = True in nonbindata
     20 return not has_nonbin_data

TypeError: argument of type 'bool' is not iterable

**Comment by MayankAgarwal** [comment]
Hi @ayushi-3536 , thank you for letting us know about the issue. I have fixed the bug in the notebook, and the experiment should work okay now.
